import os

class Config:
  SECRET_KEY=os.environ.get('SECRET_KEY')
  SQLALCHEMY_TRACK_MODIFICATIONS=False
  SQLALCHEMY_DATABASE_URI=os.environ.get('DATABASE_URL')
  SQLALCHEMY_ECHO=True
  APCA_API_BASE_URL=os.environ.get('APCA_API_BASE_URL')
  APCA_API_KEY_ID=os.environ.get('APCA_API_KEY_ID')
  APCA_API_SECRET_KEY=os.environ.get('APCA_API_SECRET_KEY')
