"""empty message

Revision ID: 07469fb16e04
Revises: c0041f4fac9c
Create Date: 2021-06-21 12:28:23.785774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07469fb16e04'
down_revision = 'c0041f4fac9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('securityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['securityId'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_securities')
    # ### end Alembic commands ###
