"""empty message

Revision ID: 9f0156d4e36b
Revises: 07469fb16e04
Create Date: 2021-06-21 18:10:18.879595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0156d4e36b'
down_revision = '07469fb16e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_securities', sa.Column('security_id', sa.Integer(), nullable=True))
    op.add_column('user_securities', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_securities_userId_fkey', 'user_securities', type_='foreignkey')
    op.drop_constraint('user_securities_securityId_fkey', 'user_securities', type_='foreignkey')
    op.create_foreign_key(None, 'user_securities', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_securities', 'securities', ['security_id'], ['id'])
    op.drop_column('user_securities', 'userId')
    op.drop_column('user_securities', 'securityId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_securities', sa.Column('securityId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_securities', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_securities', type_='foreignkey')
    op.drop_constraint(None, 'user_securities', type_='foreignkey')
    op.create_foreign_key('user_securities_securityId_fkey', 'user_securities', 'securities', ['securityId'], ['id'])
    op.create_foreign_key('user_securities_userId_fkey', 'user_securities', 'users', ['userId'], ['id'])
    op.drop_column('user_securities', 'user_id')
    op.drop_column('user_securities', 'security_id')
    # ### end Alembic commands ###
